// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { createSignal, createEffect, createMemo, createResource, onMount, onCleanup, onError, untrack, batch, on, createRoot, mergeProps, splitProps, useTransition, observable, mapArray, indexArray, createContext, useContext, children, lazy, createDeferred, createRenderEffect, createSelector, For, Show, Switch, Match, Index, ErrorBoundary, Suspense, SuspenseList } from 'solid-js';
  export { createStore, produce, reconcile, createMutable } from 'solid-js/store';
  export { Dynamic, hydrate, render, renderToString, renderToStringAsync, renderToStream, isServer, Portal } from 'solid-js/web';
  export { fakeBrowser } from 'wxt/testing';
  export { SettingsPanel } from '../components/SettingsPanel';
  export { getCurrentWindowTabs, getActiveTab, captureScreenshot, canCaptureUrl, getAllWindowsTabs, formatTabTree, TabInfo, TabGroup, GroupedTabs, WindowInfo, BrowserTree, CaptureMessageType, CaptureMessage, CaptureResponse } from '../utils/browser-context';
  export { getPageDimensions, scrollTo, getCurrentScroll, stitchImages, FullPageCaptureResult, PageDimensions, CaptureProgress, ProgressCallback } from '../utils/full-page-screenshot';
  export { htmlToMarkdown, elementToMarkdown, formatCapturedContent, formatScreenshot, turndownService } from '../utils/markdown-converter';
  export { getOpenChamberTryCfTunnel, setOpenChamberTryCfTunnel, getOpenChamberExtraArgs, setOpenChamberExtraArgs, getOpenChamberConnectionMode, setOpenChamberConnectionMode, getOpenChamberPort, saveOpenChamberPort, getOpenChamberRemoteUrl, setOpenChamberRemoteUrl, getOpenChamberUrl, checkOpenChamberStatus, retryOpenChamberConnection, OpenChamberConnectionMode } from '../utils/openchamber-status';
  export { getConnectionMode, setConnectionMode, getOpenCodePort, saveOpenCodePort, getRemoteUrl, setRemoteUrl, getWorkspaceDirectory, setWorkspaceDirectory, isWorkspaceEnabled, setWorkspaceEnabled, getOpenCodeUrl, checkUrl, checkOpenCodeStatus, manualPortScan, retryConnection, ConnectionStatus, ConnectionMode } from '../utils/opencode-status';
  export { PLATFORMS, getConversationId, isConversationPage, isExportSupported, getPlatformConfig, getExportablePlatforms, PlatformConfig } from '../utils/platforms';
  export { DEFAULT_PLATFORMS, PRESET_PLATFORMS, PLATFORM_ICONS, getIcon, loadPlatforms, savePlatformsToStorage, OpenCodeStatus } from '../utils/shared';
  export { detectPlatform, getStartCommand, getBackgroundStartCommand, launchWindowsTerminal, launchOpenCodeInTerminal, copyToClipboard, Platform } from '../utils/terminal-launcher';
}
